# Dockerfile

# Base image
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .
COPY .env.docker ./.env

# Build the application
RUN npm run build

# Expose port
EXPOSE 3000

# Start application
CMD [ "npm", "run", "start:prod" ]
